apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: gaurdocker/hello-world
  digest: sha256:10d069be412cda508b7eb17aac279dab02727979867dd94029622c682665285b
